//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer_Manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int ID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Height { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> Jerseynumber { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> Playedgames { get; set; }
        public Nullable<int> Goals { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> TeamID { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Team Team { get; set; }
    }
}
