-- InsertSwiss.sql
--
-- Autor		: Beni Egli
-- Projekt		: HBU
-- Version		: 1.0
-- 
-- Change log
-- 28/09/2017	BEGLI	Erstellt
-- 

-- DB anwählen
use Soccer;

insert into Player (Lastname,
			Firstname,
			Height,
			Birthdate,
			Jerseynumber,
			PositionID,
			Playedgames,
			Goals,
			TeamID)

--  Keeper
	values ('Roman',
			'Bürki',
			187,
			convert(date,'14.11.1990', 104),
			21,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'Schweiz')),

			
			('Yvon',
			'Mvogo',
			190,
			convert(date,'06.06.1994', 104),
			12,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'Schweiz')),

			('Yann',
			'Sommer',
			183,
			convert(date,'17.12.1988', 104),
			1,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'Schweiz')),
-- Defender
			('Manuel',
			'Akanji',
			187,
			convert(date,'19.07.1995', 104),
			5,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Schweiz')),

			('Johannes',
			'Djourou',
			191,
			convert(date,'18.01.1987', 104),
			20,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Schweiz')),
			
			('Nico',
			'Elvedi',
			189,
			convert(date,'30.09.1996', 104),
			4,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Schweiz')),

			('Michael',
			'Lang',
			185,
			convert(date,'08.02.1991', 104),
			6,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Schweiz')),

			('Stephan',
			'Lichtsteiner',
			180,
			convert(date,'16.01.1984', 104),
			2,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Schweiz')),

			('Jacques Francois',
			'Moubandje',
			179,
			convert(date,'21.06.1990', 104),
			3,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Schweiz')),
			
			('Ricardo',
			'Rodriguez',
			180,
			convert(date,'25.08.1992', 104),
			13,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Schweiz')),
			
			('Fabian',
			'Schär',
			186,
			convert(date,'20.12.1991', 104),
			22,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Schweiz')),

-- Middlefield

			('Valon',
			'Behrami',
			184,
			convert(date,'19.04.1985', 104),
			11,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Schweiz')),
			
			('Blerim',
			'Dzemaili',
			180,
			convert(date,'12.04.1986', 104),
			15,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Schweiz')),

			('Gelson',
			'Fernandes',
			179,
			convert(date,'02.09.1986', 104),
			16,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Schweiz')),

			('Remo',
			'Freuler',
			180,
			convert(date,'15.04.1992', 104),
			8,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Schweiz')),

			('Xherdan',
			'Shaqiri',
			169,
			convert(date,'10.10.1991', 104),
			23,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Schweiz')),

			('Granit',
			'Xhaka',
			185,
			convert(date,'27.09.1992', 104),
			10,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Schweiz')),

			('Steven',
			'Zuber',
			181,
			convert(date,'17.08.1991', 104),
			14,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Schweiz')),

			('Denis Lemi',
			'Zakaria',
			191,
			convert(date,'20.11.1996', 104),
			17,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Schweiz')),

	-- Striker

	
			('Breel Donald',
			'Embolo',
			184,
			convert(date,'14.02.1997', 104),
			7,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Schweiz')),

			
			('Josip',
			'Drmic',
			182,
			convert(date,'08.08.1992', 104),
			19,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Schweiz')),

			('Mario',
			'Gavranovic',
			175,
			convert(date,'24.11.1989', 104),
			18,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Schweiz')),

			('Haris',
			'Seferovic',
			187,
			convert(date,'22.02.1992', 104),
			9,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Schweiz'))
	
	

	select *  from Player;
	go
