-- InsertGreatBritian.sql
--
-- Autor		: Beni Egli
-- Projekt		: HBU
-- Version		: 1.0
-- 
-- Change log
-- 28/09/2017	BEGLI	Erstellt
-- 

-- DB anwählen
use Soccer;

insert into Player (Lastname,
			Firstname,
			Height,
			Birthdate,
			Jerseynumber,
			PositionID,
			Playedgames,
			Goals,
			TeamID)

--  Keeper
	values ('Jordan',
			'Pickford',
			185,
			convert(date,'07.03.1994', 104),
			1,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'England')),

			
			('Jack',
			'Butland',
			196,
			convert(date,'10.03.1993', 104),
			1,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'England')),

			('Nick',
			'Pope',
			191,
			convert(date,'19.04.1992', 104),
			29,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'England')),
-- Defender
			('John',
			'Stones',
			188,
			convert(date,'28.05.1994', 104),
			5,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'England')),

			('Harry',
			'Maguire',
			194,
			convert(date,'05.03.1993', 104),
			15,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'England')),
			
			('Phil',
			'Jones',
			185,
			convert(date,'21.02.1992', 104),
			4,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'England')),

			('Gary',
			'Cahill',
			193,
			convert(date,'19.12.1985', 104),
			24,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'England')),

			('Danny',
			'Rose',
			173,
			convert(date,'02.07.1990', 104),
			3,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'England')),

			('Kyle',
			'Walker',
			181,
			convert(date,'28.05.1990', 104),
			2,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'England')),
			
			('Trent',
			'Alexander-Arnold',
			180,
			convert(date,'07.10.1998', 104),
			66,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'England')),
			
			('Kieran',
			'Trippier',
			174,
			convert(date,'19.09.1990', 104),
			2,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'England')),

-- Middlefield

			('Eric',
			'Dier',
			189,
			convert(date,'15.01.1994', 104),
			15,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'England')),
			
			('Jordan',
			'Henderson',
			187,
			convert(date,'17.06.1990', 104),
			14,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'England')),

			('Fabian',
			'Delph',
			174,
			convert(date,'21.11.1989', 104),
			18,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'England')),

			('Ruben',
			'Loftus-Cheek',
			191,
			convert(date,'23.01.1996', 104),
			11,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'England')),

			('Ashley',
			'Young',
			176,
			convert(date,'09.07.1985', 104),
			18,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'England')),

			('Dele',
			'Alli',
			188,
			convert(date,'11.04.1996', 104),
			20,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'England')),

			('Jesse',
			'Lingard',
			174,
			convert(date,'15.12.1992', 104),
			14,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'England')),

			('Raheem',
			'Sterling',
			170,
			convert(date,'08.12.1994', 104),
			7,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'England')),

	-- Striker

	
			('Harry',
			'Kane',
			188,
			convert(date,'28.07.1993', 104),
			10,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'England')),

			
			('Marcus',
			'Rashford',
			185,
			convert(date,'31.10.1997', 104),
			19,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'England')),

			('Jamie',
			'Vardy',
			179,
			convert(date,'11.01.1987', 104),
			9,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'England')),

			('Danny',
			'Welbeck',
			183,
			convert(date,'26.11.1990', 104),
			23,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'England'))
	
	

	select *  from Player;
	go
