-- InsertFrench.sql
--
-- Autor		: Beni Egli
-- Projekt		: HBU
-- Version		: 1.0
-- 
-- Change log
-- 28/09/2017	BEGLI	Erstellt
-- 

-- DB anwählen
use Soccer;

insert into Player (Lastname,
			Firstname,
			Height,
			Birthdate,
			Jerseynumber,
			PositionID,
			Playedgames,
			Goals,
			TeamID)

--  Keeper
	values ('Hugo',
			'Lloris',
			188,
			convert(date,'26.12.1986', 104),
			1,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'Frankreich')),

			
			('Alphonse',
			'Areola',
			195,
			convert(date,'27.02.1993', 104),
			16,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'Frankreich')),

			('Steve',
			'Mandanda',
			185,
			convert(date,'28.03.1985', 104),
			30,
			(select id from Position where Position = 'Keeper'),
			10,
			0,
			(select id from Team where Team = 'Frankreich')),
-- Defender
			('Raphael',
			'Varane',
			191,
			convert(date,'25.04.1993', 104),
			5,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Frankreich')),

			('Samuel',
			'Umtiti',
			181,
			convert(date,'14.11.1993', 104),
			23,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Frankreich')),
			
			('Benjamin',
			'Pavard',
			186,
			convert(date,'28.03.1996', 104),
			21,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Frankreich')),

			('Presnel',
			'Kimpembe',
			183,
			convert(date,'13.08.1995', 104),
			3,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Frankreich')),

			('Adil',
			'Rami',
			190,
			convert(date,'27.12.1985', 104),
			23,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Frankreich')),

			('Benjamin',
			'Mendy',
			185,
			convert(date,'17.07.1994', 104),
			22,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Frankreich')),
			
			('Lucas',
			'Hernandez',
			184,
			convert(date,'14.02.1996', 104),
			19,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Frankreich')),
			
			('Djibril',
			'Sidibe',
			182,
			convert(date,'29.07.1992', 104),
			19,
			(select id from Position where Position = 'Defender'),
			10,
			5,
			(select id from Team where Team = 'Frankreich')),

-- Middlefield

			('NGolo',
			'Kanté',
			168,
			convert(date,'29.03.1991', 104),
			7,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Frankreich')),
			
			('Steven',
			'Nzonzi',
			196,
			convert(date,'15.12.1988', 104),
			15,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Frankreich')),

			('Paul',
			'Pogba',
			191,
			convert(date,'15.03.1993', 104),
			6,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Frankreich')),

			('Corentin',
			'Tolisso',
			181,
			convert(date,'03.08.1994', 104),
			24,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Frankreich')),

			('Blaise',
			'Matuidi',
			180,
			convert(date,'09.04.1987', 104),
			14,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Frankreich')),

			('Nabil',
			'Fekir',
			173,
			convert(date,'18.07.1993', 104),
			18,
			(select id from Position where Position = 'Middlefield'),
			10,
			10,
			(select id from Team where Team = 'Frankreich')),

			-- Striker


			('Thomas',
			'Lemar',
			170,
			convert(date,'12.1.1995', 104),
			27,
			(select id from Position where Position = 'Striker'),
			10,
			10,
			(select id from Team where Team = 'Frankreich')),
			
			('Denis Lemi',
			'Zakaria',
			191,
			convert(date,'12.11.1995', 104),
			27,
			(select id from Position where Position = 'Striker'),
			10,
			10,
			(select id from Team where Team = 'Frankreich')),

				
			('Kylian',
			'Mbappé',
			178,
			convert(date,'20.12.1998', 104),
			29,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Frankreich')),

			
			('Ousmane',
			'Dembélé',
			178,
			convert(date,'15.05.1997', 104),
			11,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Frankreich')),

			('Flarian',
			'Thauvin',
			179,
			convert(date,'26.01.1993', 104),
			26,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Frankreich')),

			('Antoine',
			'Griezmann',
			175,
			convert(date,'21.03.1991', 104),
			7,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Frankreich')),
			
			
			('Olivier',
			'Giroud',
			192,
			convert(date,'30.09.1986', 104),
			18,
			(select id from Position where Position = 'Striker'),
			10,
			20,
			(select id from Team where Team = 'Frankreich'))
	

	select *  from Player;
	go
